Develop
vladyslav-ko/taf-rp-launches pull request #1
Opened 2023-04-13 12:30 UTC by vladyslav-ko

2023-04-13 13:06 UTC, sforktesting approved these changes

2023-04-16 16:59 UTC, dkatsechau requested changes

2023-04-16 16:59 UTC, dkatsechau commented on .github/workflows/maven.yml
> +      run: mvn clean compile
How about to compile tests also?

2023-04-16 16:59 UTC, dkatsechau commented on pom.xml
> +      <artifactId>selenium-edge-driver</artifactId>
I recommend to not to use exact driver dependencies and use [webdrivermanager](https://github.com/bonigarcia/webdrivermanager)
It will be required in web-UI module, and this module will pass like it is now.

2023-04-16 16:59 UTC, dkatsechau commented on pom.xml
> +          <source>8</source>
Do you need Java 8 here?
Your Github build workflow uses 11.

2023-04-16 16:59 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    Logger log = LogManager.getLogger("OpenLaunchByIdTest.java");
Please, use class name, not String.

2023-04-16 16:59 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    private final String launchId = "5";
Please, follow Java code convention for constants: UPPER_CASE_WITH_UNDERSCORES.
Also constant is static.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +    public static WebDriver driver;
Why not private?
And did you think about how will you use it in multithreaded test runs?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +        driver.manage().timeouts().implicitlyWait(Constants.IMPLICIT_TIME, TimeUnit.SECONDS);
Two equal lines.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +        driver.get(ConfigReader.getProperty("url"));
You will face problems when your tests will need other starting URL.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        driver.get(ConfigReader.getProperty("url"));
You already get this URL in setUp method, why duplicate?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void loginButton() {
What does this method execute?
Please, name method properly.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +public class LoginPage extends BasePage{
Please, format your code with default auto-formatter before commiting it.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterUsernameField(String userName) {
Maybe something like ```public void fillUsernameInput(String username)```?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterPasswordField(String password) {
Maybe something like ```public void inputPassword(String password)```?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    CommonMethods commonMethods = new CommonMethods();
BasePage extends CommonMethods and also contains CommonMethods objects iside.
Maybe try not to use inheritance and use structural design patterns instead?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +public class CommonMethods extends DriverBuilder {
Why does this class extend DriverBuilder?
Maybe remake DriverBuilder using some creational design patterns and not extend it?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +
minor: in some classes you have this empty line, in some you don't. Please, choose one approach (any you want) and adhere it.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
Not needed empty line.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
Not needed empty line.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +    public static void readProperties(String filePath) {
Do you have other properties files right now?
If not, maybe embed this reading file logic into class constructor or static code block?

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +    static final String USER_DIR = System.getProperty("user.dir");
Why package-private access modifier?

2023-04-16 16:59 UTC, dkatsechau commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
Please, do not store passwords in VCS.

2023-04-16 16:59 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    static void closeBrowser() {
Maybe extend this class from BaseTest, not from CommonMethods, and use @AfterAll inside the BaseTest class?
It implies, of course, using creational pattern to be able to get WebDriver from any place in your code.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +            e.printStackTrace();
Please, log exception also using logger.

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
10 - [magic number.](https://en.wikipedia.org/wiki/Magic_number_(programming))

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
10 - [magic number.](https://en.wikipedia.org/wiki/Magic_number_(programming))

2023-04-16 16:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        setUp();
Why do you set up driver in the step?
Maybe use @Before methods inside of test classes for this purpose?

2023-04-17 11:31 UTC, vladyslav-ko commented on .github/workflows/maven.yml
> +      run: mvn clean compile
Do you mean run tests?

2023-04-17 12:07 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +    public static WebDriver driver;
Changed the driver variable to a ThreadLocal to allow for multithreading.

2023-04-17 13:49 UTC, vladyslav-ko commented on pom.xml
> +      <artifactId>selenium-edge-driver</artifactId>
When it will be required, I will add this in scope of web-UI module

2023-04-17 13:51 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        driver.get(ConfigReader.getProperty("url"));
I have deleted it

2023-04-17 13:53 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +    public static void readProperties(String filePath) {
Maybe I will need to create other properties files in scope of another modules. So I would like to leave this part of code, as it is looks like now.

2023-04-17 13:55 UTC, vladyslav-ko commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
What do I need to do? Just don't add this file to VCS?

2023-04-17 19:00 UTC, dkatsechau commented on .github/workflows/maven.yml
> +      run: mvn clean compile
I mean test-compile Maven phase. There is a difference between compile, test-compile and test.
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

2023-04-17 19:01 UTC, dkatsechau commented on pom.xml
> +          <source>8</source>
Did you change something?

2023-04-17 19:02 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    Logger log = LogManager.getLogger("OpenLaunchByIdTest.java");
Did you change something?

2023-04-17 19:02 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    private final String launchId = "5";
Did you change something?

2023-04-17 19:05 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +    public static WebDriver driver;
Please, don't resolve another's questions, let topic started to read your answer and resolve conversation.

2023-04-17 19:05 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +        driver.manage().timeouts().implicitlyWait(Constants.IMPLICIT_TIME, TimeUnit.SECONDS);
Did you change something?

2023-04-17 19:06 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +        driver.get(ConfigReader.getProperty("url"));
Please, don't resolve another's questions, let topic started to read your answer and resolve conversation.

2023-04-17 19:06 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        driver.get(ConfigReader.getProperty("url"));
Please, don't resolve another's questions, let topic started to read your answer and resolve conversation.

2023-04-17 19:06 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void loginButton() {
Did you change something?

2023-04-17 19:06 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +public class LoginPage extends BasePage{
Did you change something?

2023-04-17 19:07 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterUsernameField(String userName) {
Did you change something?

2023-04-17 19:08 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterPasswordField(String password) {
Did you change something?

2023-04-17 19:08 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterPasswordField(String password) {
Did you change something?

2023-04-17 19:08 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    CommonMethods commonMethods = new CommonMethods();
Did you change something?

2023-04-17 19:08 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +public class CommonMethods extends DriverBuilder {
Did you change something?

2023-04-17 19:09 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +
Did you change something?

2023-04-17 19:09 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
Did you change something?

2023-04-17 19:09 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
Did you change something?

2023-04-17 19:10 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
Did you change something?

2023-04-17 19:11 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +    static final String USER_DIR = System.getProperty("user.dir");
Did you change something?

2023-04-17 19:11 UTC, dkatsechau commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
Do not commit sensitive properties values in VCS.

2023-04-17 19:11 UTC, dkatsechau commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    static void closeBrowser() {
Did you change something?

2023-04-17 19:12 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +            e.printStackTrace();
Did you change something?

2023-04-17 19:12 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
Did you change something?

2023-04-17 19:12 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
Did you change something?

2023-04-17 19:12 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        setUp();
Did you change something?

2023-04-18 20:21 UTC, vladyslav-ko commented on pom.xml
> +          <source>8</source>
Yes, i changed version to 11

2023-04-18 20:23 UTC, vladyslav-ko commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    Logger log = LogManager.getLogger("OpenLaunchByIdTest.java");
I moved logger from this class to Base.class

2023-04-18 20:23 UTC, vladyslav-ko commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    private final String launchId = "5";
private static final String LAUNCH_ID = "5";

2023-04-18 20:24 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +    public static WebDriver driver;
I added to this class some new code:
private static final ThreadLocal<WebDriver> driver = new ThreadLocal<>();
    private static final Logger log = LogManager.getLogger(DriverBuilder.class);

    public static WebDriver getDriver() {
        if (driver.get() == null) {
            driver.set(createDriver());
        }
        return driver.get();
    }

2023-04-18 20:26 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        driver.get(ConfigReader.getProperty("url"));
I use this line of code only in DriverBuilder.class
newDriver.get(ConfigReader.getProperty("url"));

2023-04-18 20:26 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void loginButton() {
Method name - clickOnLoginButton

2023-04-18 20:27 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +public class LoginPage extends BasePage{
I have formatted all code with default auto-formatter

2023-04-18 20:28 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterUsernameField(String userName) {
Method name - enterUsername

2023-04-18 20:28 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LoginPage.java
> +    public void enterPasswordField(String password) {
Method name - enterPassword

2023-04-18 20:29 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    CommonMethods commonMethods = new CommonMethods();
I deleted CommonMethods objects inside BasePage

2023-04-18 20:40 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +public class CommonMethods extends DriverBuilder {
I deleted extending from CommonMethods.class and added private constructor to DriverBuilder.class

2023-04-18 20:41 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/DriverBuilder.java
> +
Ideleted this line everywhere

2023-04-18 20:41 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
I deleted this line everywhere

2023-04-18 20:41 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
I deleted this line everywhere

2023-04-18 20:42 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +    static final String USER_DIR = System.getProperty("user.dir");
I have changed it to private

2023-04-18 20:43 UTC, vladyslav-ko commented on src/test/java/tests/OpenLaunchByIdTest.java
> +    static void closeBrowser() {
I created Base.class and it contains @BeforeAll and @AfterAll

2023-04-18 20:45 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +            e.printStackTrace();
log.error("IOException while reading properties file: " + e.getMessage());

2023-04-18 20:46 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
private static final int WAITING_TIME = 10;
WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(WAITING_TIME));

2023-04-18 20:46 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
private static final int WAITING_TIME = 10;
WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(WAITING_TIME));

2023-04-18 20:46 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        setUp();
I created Base.class and it contains @BeforeAll and @Afterall

2023-04-18 20:58 UTC, vladyslav-ko commented on .github/workflows/maven.yml
> +      run: mvn clean compile
I added this and build is green

2023-04-18 20:59 UTC, vladyslav-ko commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
I deleted configuration.properties and reportportal.properties from git and add *.properties to gitignore file

2023-04-19 05:59 UTC, dkatsechau requested changes

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +public class CommonMethods extends DriverBuilder {
Why do you extend DriverBuilder?
One of the basic design principles: Composition over Inheritance.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +   private static final String USER_DIR = System.getProperty("user.dir");
Identation.

2023-04-19 05:59 UTC, dkatsechau commented on src/test/java/tests/Base.java
> +}
Please, add empty line at the end of the files.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +
Not needed empty line.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +
Not needed empty line.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +   private static final String USER_DIR = System.getProperty("user.dir");
Identation.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +    static Logger log = LogManager.getLogger(ConfigReader.class);
Why package-private?

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +
It is still present.

2023-04-19 05:59 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +public class BasePage extends CommonMethods {
Why do you extend this? How about to use composition?

2023-04-19 05:59 UTC, dkatsechau commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
Your code is dependent of this files - properties files are essential parts of your framework.
I told only about **values**, not properties themselves.

2023-04-19 08:21 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/ConfigReader.java
> +    static Logger log = LogManager.getLogger(ConfigReader.class);
Change to private

2023-04-19 08:22 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/utils/Constants.java
> +
Deleted

2023-04-19 08:47 UTC, vladyslav-ko commented on src/test/java/tests/Base.java
> +}
I would like not to add it

2023-04-19 08:50 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +public class CommonMethods extends DriverBuilder {
![image](https://user-images.githubusercontent.com/78149137/233021840-44c0e731-4235-4093-b870-d8b50ac74b8d.png)

2023-04-19 08:51 UTC, vladyslav-ko commented on src/test/java/resources/configs/configuration.properties
> +adminPassword = erebus
![image](https://user-images.githubusercontent.com/78149137/233022292-cb116698-f853-4810-86e9-436b8bb5b01a.png)

2023-04-19 17:44 UTC, dkatsechau approved these changes

2023-04-19 17:44 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    private CommonMethods commonMethods = new CommonMethods();;
two semicolons

2023-04-19 17:46 UTC, merged