qa: test runners home task
vladyslav-ko/taf-rp-launches pull request #2
Opened 2023-04-25 14:10 UTC by vladyslav-ko

2023-04-25 14:14 UTC, sforktesting submitted a review, later dismissed

2023-05-01 17:10 UTC, vikatyshchenko requested changes

2023-05-01 17:10 UTC, vikatyshchenko commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +                    "(//*[@data-id='%s']//*[@class='executionStatistics__execution-statistics--1iek7']/a)[2]",
Why not store locators as variables to reuse them?
Or use @FindBy annotations?

2023-05-01 17:10 UTC, vikatyshchenko commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
> +        launchesPage.selectLaunchBlockById(launchId);
Wouldn't it be better for methods to return an instance of a Steps class to provide less code duplication and make tests more readable?

2023-05-01 19:29 UTC, vladyslav-ko commented on test-output/Default Suite/taf-rp-launches.html
It was generated automatically. I deleted this package from branch and added this package to gitignore.

2023-05-01 19:32 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +                    "(//*[@data-id='%s']//*[@class='executionStatistics__execution-statistics--1iek7']/a)[2]",
I will do this in BDD home work.

2023-05-02 05:51 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
> +        launchesPage.selectLaunchBlockById(launchId);
However, in scope of this task this comment is valid.
Each PR is atomic and can not refer to the further modules.

2023-05-02 05:52 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +                    "(//*[@data-id='%s']//*[@class='executionStatistics__execution-statistics--1iek7']/a)[2]",
Please, do not refer to the further modules. This PR is not about BDD.

2023-05-02 08:46 UTC, sforktesting requested changes

2023-05-02 08:47 UTC, vladyslav-ko commented on src/test/java/tests/junit/BaseJunit.java
> +    static LoginSteps loginSteps = new LoginSteps();
I fully agree with you. I will delete it.

2023-05-02 09:31 UTC, sforktesting approved these changes

2023-05-02 09:32 UTC, vladyslav-ko commented on test-output/Default Suite/taf-rp-launches.xml
It was generated automatically. I deleted this package from branch and added this package to gitignore.

2023-05-02 09:33 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +                    "(//*[@data-id='%s']//*[@class='executionStatistics__execution-statistics--1iek7']/a)[2]",
Xpathes were moved into variables

2023-05-02 10:36 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
> +        launchesPage.selectLaunchBlockById(launchId);
For me it is more readable when I write method after method, like:
launchSteps.clickOnButton();
launchSteps.selectElement(id);
launchSteps.selectAnotherElement(number);
Than it wil be like - launchSteps.clickOnButton().selectElement(id).selectAnotherElement(number);

2023-05-03 11:24 UTC, vikatyshchenko approved these changes

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +    public static final String LAUNCH_BLOCK = "(//*[@class='gridRow__grid-row-wrapper--1dI9K' and @data-id='%s']//*[@class='itemInfo__name-link--1ItPc'])[1]";
All this constants can be private.
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/SmokeTestNgTests3.java
> +            {"5", "Demo Api Tests", "29 days ago"},
Is it still working with constant ```29 days ago```?
Are all tests passing without issues?

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/SmokeTestNgTests2.java
> +
Minor: Why again different format for empty lines?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/junit/SmokeJunitTests.java
> +    @ExtendWith(ReportPortalExtension.class)
Why use this annotation on methods, not on types?
Is it meant for something?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/BaseTestNg.java
> +    public void openAndLogin() throws InterruptedException {
Why this exception is throwing?

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/junit/BaseJunit.java
> +    Logger log = LogManager.getLogger(CommonMethods.class);
Why does Logger for BaseJinit class use CommonMethods class?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/BaseTestNg.java
> +        getDriver();
Why do you init driver for the entire test class?
Are your test methods linked inside the test class?

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +    public List<String> getElementTexts(String xpath) {
Method is not used anywhere.

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        for (WebElement element : elements) {
Why not to use stream?

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
> +import java.util.List;
Not used import.

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +        return getCommonMethods().getText(totalAmountOfTestsInBlock);
Why access static method from instance reference?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/BaseTestNg.java
> +    public void navigateToLaunchesAndCloseBrowser() {
Why do this method have such name?

2023-05-04 14:39 UTC, dkatsechau commented on src/test/java/tests/testng/SelectLaunchByIdAndCheckSuiteDescriptionTestNgTest.java
> +    public Object[][] testDataSelectLaunchById() {
Your dataprovider, befoclass and afterclass methods are public,
whyle test method are package-private
Is it for purpose?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/steps/SuiteSteps.java
> +    SuitePage suitePage = new SuitePage();
Why not private?

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
>      LaunchesPage launchesPage = new LaunchesPage();
Why not private?
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/SuitePage.java
> +            By.xpath(String.format(SUITE_NAME,elementId)));
Why not formatted? Space should be placed after comma.
Here and in other places.

2023-05-04 14:39 UTC, dkatsechau commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    public static final String LAUNCHES_BUTTON = "//div[@class='sidebarButton__sidebar-nav-btn--1prEO']/a[contains(@href,'launches')]";
What was happened with file organization?
Code Conventions for the Java: https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2023-05-04 20:11 UTC, vladyslav-ko commented on src/test/java/tests/junit/SmokeJunitTests.java
> +    @ExtendWith(ReportPortalExtension.class)
@ExtendWith(ReportPortalExtension.class): This annotation is from the JUnit Jupiter framework and is used to register the ReportPortalExtension class as an extension for the test class. It allows the integration of the ReportPortal reporting tool with the test execution.

@Execution(ExecutionMode.CONCURRENT): This annotation is used to specify the execution mode of the test class. In this case, the value is set to ExecutionMode.CONCURRENT, which means that the test methods in this class can be executed concurrently.

@ParameterizedTest: This annotation is from the JUnit Jupiter framework and is used to indicate that the annotated method is a parameterized test. Parameterized tests allow you to run the same test method multiple times with different arguments.

@CsvSource: This annotation is used to provide comma-separated values (CSV) as a source for the parameterized test. Each row in the CSV represents a set of arguments for a test invocation.

@ValueSource: This annotation is used to provide a single-dimensional array of values as a source for the parameterized test. Each value in the array represents an argument for a test invocation.

2023-05-04 20:12 UTC, vladyslav-ko commented on src/test/java/tests/testng/BaseTestNg.java
> +    public void openAndLogin() throws InterruptedException {
I have no idea)
I will delete this

2023-05-04 20:13 UTC, vladyslav-ko commented on src/test/java/tests/junit/BaseJunit.java
> +    Logger log = LogManager.getLogger(CommonMethods.class);
I will fix it

2023-05-04 20:17 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +    public List<String> getElementTexts(String xpath) {
I will delete it

2023-05-04 20:18 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/testbase/CommonMethods.java
> +        for (WebElement element : elements) {
According to the previous comment, I will delete this method.

2023-05-04 20:22 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
> +import java.util.List;
I will delete it

2023-05-04 20:23 UTC, vladyslav-ko commented on src/test/java/tests/testng/BaseTestNg.java
> +    public void navigateToLaunchesAndCloseBrowser() {
i will rename it - closeBrowser

2023-05-04 20:26 UTC, vladyslav-ko commented on src/test/java/tests/testng/SelectLaunchByIdAndCheckSuiteDescriptionTestNgTest.java
> +    public Object[][] testDataSelectLaunchById() {
It doesn't have any purpose. All test methods now are public.

2023-05-04 20:33 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/SuitePage.java
> +            By.xpath(String.format(SUITE_NAME,elementId)));
now it is formatted

2023-05-04 20:46 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/BasePage.java
> +    public static final String LAUNCHES_BUTTON = "//div[@class='sidebarButton__sidebar-nav-btn--1prEO']/a[contains(@href,'launches')]";
I apologize for this. Now we have:
- private static final
- private final

2023-05-04 20:46 UTC, vladyslav-ko commented on src/test/java/tests/testng/SmokeTestNgTests3.java
> +public class SmokeTestNgTests3 extends BaseTestNg{
fixed

2023-05-04 20:47 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/BasePage.java
>      public void launchesButton() {
fixed

2023-05-04 20:47 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +    public static final String LAUNCH_BLOCK = "(//*[@class='gridRow__grid-row-wrapper--1dI9K' and @data-id='%s']//*[@class='itemInfo__name-link--1ItPc'])[1]";
fixed

2023-05-04 20:49 UTC, vladyslav-ko commented on src/test/java/tests/testng/SmokeTestNgTests3.java
> +            {"5", "Demo Api Tests", "29 days ago"},
When i created this PR - all tests were green. Now I have some problems with docker, when i resolve them, I will change data for tests and attach the screenshot with green run.

2023-05-04 20:49 UTC, vladyslav-ko commented on src/test/java/tests/testng/SmokeTestNgTests2.java
> +
Now everything in one code style.

2023-05-04 20:50 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/steps/SuiteSteps.java
> +    SuitePage suitePage = new SuitePage();
private now

2023-05-04 20:50 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/steps/LaunchesSteps.java
>      LaunchesPage launchesPage = new LaunchesPage();
private now

2023-05-05 04:00 UTC, dkatsechau commented on src/test/java/tests/junit/SmokeJunitTests.java
> +    @ExtendWith(ReportPortalExtension.class)
I only asked about one annotation, that I was commented.
Did you use it on types? Does it work when used on types?

2023-05-05 04:05 UTC, dkatsechau commented on src/test/java/tests/testng/BaseTestNg.java
> +        getDriver();
Somehow you create new driver in Junit```@BeforeEach``` annotated method - and it's ok.
Please, don't create driver for class, unless your tests are binded with consecutive logic.

2023-05-05 08:34 UTC, vladyslav-ko commented on src/main/java/com/reportportal/qa/pages/LaunchesPage.java
> +        return getCommonMethods().getText(totalAmountOfTestsInBlock);
fixed

2023-05-05 08:57 UTC, vladyslav-ko commented on src/test/java/tests/junit/SmokeJunitTests.java
> +    @ExtendWith(ReportPortalExtension.class)
Move this annotation to class
![image](https://user-images.githubusercontent.com/78149137/236416771-12fba6ab-f3bc-48f0-8740-23c1412c764d.png)

2023-05-05 09:01 UTC, vladyslav-ko commented on src/test/java/tests/testng/BaseTestNg.java
> +        getDriver();
![image](https://user-images.githubusercontent.com/78149137/236417612-10718441-3229-4e2e-af45-9715f14ef497.png)

2023-05-05 18:16 UTC, dkatsechau commented on pom.xml
> +      <groupId>io.cucumber</groupId>
Do we cucumber dependencies this now?

2023-05-05 18:21 UTC, merged